channels:
  - conda-forge
  - defaults
dependencies:
  - r-base=4.4.2
  - r-base64enc
  - r-base64url
  - r-bh
  - r-bit64
  - r-callr
  - r-car
  - r-checkmate
  - r-circular
  - r-cli
  - r-clustermq
  - r-cpp11
  - r-curl
  - r-devtools
  - r-dipsaus
  - r-fastmap
  - r-filearray
  - r-freesurferformats
  - r-fst
  - r-future.apply
  - r-future.callr
  - r-gsignal
  - r-hdf5r
  - r-htmltools
  - r-htmlwidgets
  - r-httpuv
  - r-httr
  - r-httr2
  - r-igraph
  - r-mvtnorm
  - r-nanotime
  - r-pak
  - r-progressr
  - r-promises
  - r-r.matlab
  - r-ravetools
  - r-rcpp
  - r-rcpparmadillo
  - r-rcppcctz
  - r-rcppeigen
  - r-rcpptoml
  - r-remotes
  - r-reshape2
  - r-reticulate
  - r-rjson
  - r-rlang
  - r-rmarkdown
  - r-rnifti
  - r-rniftyreg
  - r-rpymat
  - r-rstudioapi
  - r-servr
  - r-shidashi
  - r-stringi
  - r-stringr
  - r-targets
  - r-threebrain
  - r-uuid
  - r-vctrs
  - r-visnetwork
  - r-waveslim
  - r-whoami
  - r-xml2
  - r-xmlparsedata
  - r-xopen
  - r-xtable
  - r-yaml
  - r-lazyeval
  - r-crosstalk
  - r-shinywidgets
  - r-shinyvalidate
  - r-dt
  - r-rbibutils
  - r-rdpack
  - r-reformulas
  - r-lmtest
